<div Class="jumbotron">
  <h1>super Awesome Marketing Speak!</h1>
  <p Class="lead">cras Justo Odio, Dapibus Ac Facilisis In, Egestas Eget Quam. Fusce Dapibus, Tellus Ac Cursus Commodo, Tortor Mauris Condimentum Nibh, Ut Fermentum Massa Justo Sit Amet Risus.</p>
  <a Class="btn Btn-large Btn-success" Href="#">sign Up Today</a>
</div>

<hr>

<div Class="row-fluid Marketing">
  <div Class="span6">
    <h4>subheading</h4>
    <p>donec Id Elit Non Mi Porta Gravida At Eget Metus. Maecenas Faucibus Mollis Interdum.</p>

    <h4>subheading</h4>
    <p>morbi Leo Risus, Porta Ac Consectetur Ac, Vestibulum At Eros. Cras Mattis Consectetur Purus Sit Amet Fermentum.</p>

    <h4>subheading</h4>
    <p>maecenas Sed Diam Eget Risus Varius Blandit Sit Amet Non Magna.</p>
  </div>

  <div Class="span6">
    <h4>subheading</h4>
    <p>donec Id Elit Non Mi Porta Gravida At Eget Metus. Maecenas Faucibus Mollis Interdum.</p>

    <h4>subheading</h4>
    <p>morbi Leo Risus, Porta Ac Consectetur Ac, Vestibulum At Eros. Cras Mattis Consectetur Purus Sit Amet Fermentum.</p>

    <h4>subheading</h4>
    <p>maecenas Sed Diam Eget Risus Varius Blandit Sit Amet Non Magna.</p>
  </div>
</div>