<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bootphp CMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- bootphp theme -->
    <link href="/themes/bootphp/css/style.css" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>

    <!-- jien -->
    <script src="/js/jien.js"></script>
    <link href="/js/editable/editable.css" rel="stylesheet">
    <script src="/js/editable/editable.js"></script>

</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li class="active "><a href="/">Home</a></li>
            <li class=""><a href="/about">About</a></li>
            <li class=""><a href="/contact">Contact</a></li>
        </ul>
        <h3 class="muted">Bootphp CMS</h3>
    </div>

    <hr>

    <?php echo $this->layout()->content; ?>
    <hr>

    <div class="footer">
        <p>&copy; Company 2013</p>
    </div>

</div> <!-- /container -->


</body>
</html>