<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo $this->title; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.14.1/build/cssreset-context/cssreset-context-min.css">

    <!-- bootphp theme -->
    <link href="/themes/bootphp/css/style.css" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>

    <!-- jien files -->
    <script src="https://api.filepicker.io/v1/filepicker.js"></script>
    <script type="text/javascript">filepicker.setKey('<?php echo FILEPICKER_KEY; ?>');</script>
    <script src="/js/jien.js" type="text/javascript"></script>
    <script src="/js/plugins/colorbox/jquery.colorbox.js" type="text/javascript"></script>
    <link rel='stylesheet' href='/js/plugins/colorbox/example4/colorbox.css' type='text/css' media='screen' />
    <link href="/js/editable/editable.css" rel="stylesheet">
    <script src="/js/editable/editable.js"></script>

</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul id='mainmenu' class="nav nav-pills pull-right">
            <li><a href="/">Home</a></li>
            <?php
            $pages = Jien::model("Page")->get()->rows();
            foreach($pages AS $key=>$value){
            ?>
            <li><a href="<?php echo $value['permalink']; ?>"><?php echo $value['title']; ?></a></li>
            <?php } ?>

        </ul>
        <h3 class="muted"><?php echo $this->title; ?></h3>
    </div>

    <hr>

    <?php echo $this->layout()->content; ?>
    <hr>

    <div class="footer">
        <p>&copy; Company 2013</p>
    </div>

</div> <!-- /container -->

<script>
    $(document).ready(function(){
        var uri = window.location.href.toString().split(window.location.host)[1];
        $('#mainmenu li').removeClass('active');
        $('#mainmenu li a').each(function(el){
            var href = $(this).attr('href');
            if(href == uri){
                $(this).parent().addClass('active');
            }
        })
    })
</script>

</body>
</html>