<!-- MAIN CONTAINER -->
<div id="content">
	<div class="one">
		<!-- COLUMNS CONTAINER STARTS-->
		<div class="intro-pages">
			<!-- INTRO DIV STARTS-->
			<?php echo $this->editable('page_layout_header', 'text', '<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what\'s &quot;Adventure&quot; capable to do for You.Enjoy!</h3>'); ?>
		</div>
		<!-- INTRO ENDS-->
	</div>
	<!-- COLUMNS CONTAINER ENDS-->
	<div class="one">
		<div class="one-fourth">
			<?php echo $this->partial('partials/pages.phtml'); ?>
		</div>
		<div class="inner-content last">
			<?php

			// page found from db
			if(!empty($this->content)){
				echo $this->content;

			// load from static file
			}else{
				echo $this->partial($this->file);
			}
			?>
		</div>

	</div>
	<!-- CONTENT ENDS-->
</div>