<!-- MAIN CONTAINER -->
<div id="content">
	<div class="one">
		<!-- COLUMNS CONTAINER STARTS-->
		<div class="intro-pages">
			<!-- INTRO DIV STARTS-->
			<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what's &quot;Adventure&quot; capable to do for You.Enjoy! </h3>
		</div>
		<!-- INTRO ENDS-->
	</div>
	<!-- COLUMNS CONTAINER ENDS-->
	<div class="one">
		<div class="pricing-table-box-container">
			<ul class="pricing-table-header">
				<li class="one">
				<h3>Plan Specifications</h3>
				</li>
				<li class="two">
				<h3>Starter</h3>
				$10.00/m </li>
				<li class="three">
				<h3>Business</h3>
				$25.00/m </li>
				<li class="four">
				<h3>Professional</h3>
				$99.00/m </li>
			</ul>
			<ul class="pricing-table-white">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-1.png" alt=""/></span>Unlimited Space</li>
				<li class="two">Unlimited</li>
				<li class="three">Unlimited</li>
				<li class="four">Unlimited</li>
			</ul>
			<ul class="pricing-table-grey">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-2.png" alt=""/></span>Unlimited Bandwidth</li>
				<li class="two"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
				<li class="three"><img src="/themes/adventure/images/icons/no.png" alt=""/></li>
				<li class="four"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
			</ul>
			<ul class="pricing-table-white">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-3.png" alt=""/></span>Unlimited Database</li>
				<li class="two">Unlimited</li>
				<li class="three">Unlimited</li>
				<li class="four">Unlimited</li>
			</ul>
			<ul class="pricing-table-grey">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-4.png" alt=""/></span>SEO Tools</li>
				<li class="two">Unlimited</li>
				<li class="three">Unlimited</li>
				<li class="four">Unlimited</li>
			</ul>
			<ul class="pricing-table-white">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-5.png" alt=""/></span>Wordpress &amp; Joomla</li>
				<li class="two">Unlimited</li>
				<li class="three">Unlimited</li>
				<li class="four">Unlimited</li>
			</ul>
			<ul class="pricing-table-grey">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-6.png" alt=""/></span>jQuery Powerd</li>
				<li class="two"><img src="/themes/adventure/images/icons/no.png" alt=""/></li>
				<li class="three"><img src="/themes/adventure/images/icons/no.png" alt=""/></li>
				<li class="four"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
			</ul>
			<ul class="pricing-table-white">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-7.png" alt=""/></span>Private URLs</li>
				<li class="two"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
				<li class="three"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
				<li class="four"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
			</ul>
			<ul class="pricing-table-grey">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-8.png" alt=""/></span>High Security</li>
				<li class="two">1</li>
				<li class="three">3</li>
				<li class="four">3</li>
			</ul>
			<ul class="pricing-table-white">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-9.png" alt=""/></span>Site Builder</li>
				<li class="two"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
				<li class="three"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
				<li class="four"><img src="/themes/adventure/images/icons/yes.png" alt=""/></li>
			</ul>
			<ul class="pricing-table-grey">
				<li class="one"><span class="icontable"><img src="/themes/adventure/images/icons/icon-4.png" alt=""/></span>Antivirus Ready</li>
				<li class="two">Unlimited</li>
				<li class="three">Unlimited</li>
				<li class="four">Unlimited</li>
			</ul>
			<ul class="tbl-price">
				<li class="one"></li>
				<li class="two"><br/><a href="#" class="button big blue">Order Now &nbsp;?</a></li>
				<li class="three"><br/><a href="#" class="button big blue">Order Now &nbsp;?</a></li>
				<li class="four"><br/><a href="#" class="button big blue">Order Now &nbsp;?</a></li>
			</ul>
			<div class="clear">
			</div>
			<!-- clear float -->
		</div>
		<!-- end pricing-table-box-container -->
	</div>
