<div class="one-third-big">

	<!-- COLUMN STARTS-->
	<blockquote class="blockquote-left">
		<img alt=" " class="img-align-left" height="60" src="/themes/adventure/images/avatar-2.jpg" width="60" />
		<p>
			Donec ac cursus turpis. Vivamus vel luctus ligula. Donec ante turpis, pellentesque eget luctus a, pellentesque placerat magna. Integer in ligula elementum mi placerat sollicitudin. Phasellus varius leo vel nisi pretium pharetra. Etiam ornare quam eget nunc imperdiet varius.<br />
			<span><strong><a href="#">John Doe</a></strong>, Some Business.</span></p>
	</blockquote>
</div>
<!-- COLUMN ENDS-->
<div class="one-third-big last">
	<!-- COLUMN STARTS-->
	<blockquote class="blockquote-right">
		<img alt=" " class="img-align-left" height="60" src="/themes/adventure/images/avatar-3.jpg" width="60" />
		<p>
			Donec ac cursus turpis. Vivamus vel luctus ligula. Donec ante turpis, pellentesque eget luctus a, pellentesque placerat magna. Integer in ligula elementum mi placerat sollicitudin. Phasellus varius leo vel nisi pretium pharetra. Etiam ornare quam eget nunc imperdiet varius.<br />
			<span><strong><a href="#">John Doe</a></strong>, Some Business.</span></p>
	</blockquote>
</div>
<!-- COLUMN ENDS-->
<div class="one-third-big">
	<!-- COLUMN STARTS-->
	<blockquote class="blockquote-left">
		<img alt=" " class="img-align-left" height="60" src="/themes/adventure/images/avatar-4.jpg" width="60" />
		<p>
			Donec ac cursus turpis. Vivamus vel luctus ligula. Donec ante turpis, pellentesque eget luctus a, pellentesque placerat magna. Integer in ligula elementum mi placerat sollicitudin. Phasellus varius leo vel nisi pretium pharetra. Etiam ornare quam eget nunc imperdiet varius.<br />
			<span><strong><a href="#">John Doe</a></strong>, Some Business.</span></p>
	</blockquote>
</div>
<!-- COLUMN ENDS-->
<div class="one-third-big last">
	<!-- COLUMN STARTS-->
	<blockquote class="blockquote-right">
		<img alt=" " class="img-align-left" height="60" src="/themes/adventure/images/avatar-5.jpg" width="60" />
		<p>
			Donec ac cursus turpis. Vivamus vel luctus ligula. Donec ante turpis, pellentesque eget luctus a, pellentesque placerat magna. Integer in ligula elementum mi placerat sollicitudin. Phasellus varius leo vel nisi pretium pharetra. Etiam ornare quam eget nunc imperdiet varius.<br />
			<span><strong><a href="#">John Doe</a></strong>, Some Business.</span></p>
	</blockquote>
</div>
<!-- COLUMN ENDS-->
<div class="one-third-big">
	<!-- COLUMN STARTS-->
	<blockquote class="blockquote-left">
		<img alt=" " class="img-align-left" height="60" src="/themes/adventure/images/avatar-6.jpg" width="60" />
		<p>
			Donec ac cursus turpis. Vivamus vel luctus ligula. Donec ante turpis, pellentesque eget luctus a, pellentesque placerat magna. Integer in ligula elementum mi placerat sollicitudin. Phasellus varius leo vel nisi pretium pharetra. Etiam ornare quam eget nunc imperdiet varius.<br />
			<span><strong><a href="#">John Doe</a></strong>, Some Business.</span></p>
	</blockquote>
</div>
<!-- COLUMN ENDS-->
<div class="one-third-big last">
	<!-- COLUMN STARTS-->
	<blockquote class="blockquote-right">
		<img alt=" " class="img-align-left" height="60" src="/themes/adventure/images/avatar-1.jpg" width="60" />
		<p>
			Donec ac cursus turpis. Vivamus vel luctus ligula. Donec ante turpis, pellentesque eget luctus a, pellentesque placerat magna. Integer in ligula elementum mi placerat sollicitudin. Phasellus varius leo vel nisi pretium pharetra. Etiam ornare quam eget nunc imperdiet varius.<br />
			<span><strong><a href="#">John Doe</a></strong>, Some Business.</span></p>
	</blockquote>
</div>
