<div class="row" id="content">
    <div id="sidebar" class="col-lg-2">

    </div><!--#sidebar-->
    
    <div class="col-lg-10">
        <div class="filters">
            <div class="show-hide btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Show <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> ID
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Type
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Category name
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked> Created
                            </label>
                        </div>
                    </li>
                    <li class="close-dropdown">
                        Apply
                    </li>
                </ul>
            </div><!--#show-hide-->
            <select class="select2" rel="type" placeholder="Limit to post type...">
                <?php
                    $category_types_rows = Jien::model("Category")->select('type')->groupBy("type")->get()->rows();
                    $category_types = array("");
                    foreach($category_types_rows AS $row){
                        $category_types[$row['type']] = $row['type'];
                    }
                    echo $this->dropdownOptions($category_types, $this->params('type', ''));
                ?>
            </select>        
        </div><!--.filters-->
        
        <table class="table table-bordered table-striped datatable with-check">
            <thead>
                <tr class="advanced-search">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                <tr>
                    <th class="col-checkbox"><input type="checkbox"></th>
                    <th rel="category.category_id">ID</th>
                    <th rel="category.type">Type</th>
                    <th rel="category.category">Category name</th>
                    <th rel="category.created">Created</th>
                    <th class="col-actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data->rows() AS $key=>$value){ ?>
                <tr>
                    <td><input type="checkbox"></td>
                    <td><?php echo $value['category_id']; ?></td>
                    <td><?php echo $value['type']; ?></td>
                    <td><?php echo $value['category']; ?></td>
                    <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
                    <td>
                        <a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[$this->primary]; ?>" class="btn btn-primary btn-action"><span class="icon-eye-open"></span></a>
                        <a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[$this->primary];; ?>" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>" class="btn btn-danger btn-action trig_delete"><span class="icon-remove"></span></a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        
    </div><!--.col-lg-10-->
    
</div><!--#content-->

<script>
var increment = 1; 
$('.show-hide .dropdown-menu li input').on("click", function(e){
    fnShowHide($(this).parent().parent().parent().index() + increment);
});

var listTable = $('.datatable').dataTable({
    "aoColumnDefs": [
        { "bSearchable": false, "bSortable": false, "aTargets": ['col-actions', 'col-checkbox', 'col-upload', 'col-ignore'] },
        { "sClass": "col-actions", "aTargets": [-1] }
    ],
    "sDom": 'T<"clear">lfrtip',
    "oTableTools": {
        "sSwfPath": "/themes/admin/swf/copy_csv_xls_pdf.swf",
        "aButtons": [
            {
                "sExtends": "xls",
                "sButtonText": '<span class="icon-share-alt"></span> Export'
            }
        ]
    }
});
</script>