<div id="title-bar" class="page-header">
    <div class="col-lg-6">
        <h1 class="page-title">Listing Page</h1>
    </div>
    <div id="header-btns">
        <div class="inner">
            <button data-model="Page" class="btn btn-default trig_model_search">Search</button>
            <a href="/admin/page" class="btn btn-default"><span class="icon-plus"></span> Add New Page</a>
        </div><!--.inner-->
    </div><!--#header-btns.col-lg-4-->
</div>

<div class="row">
    <div class="col-sm-2">

    </div>
</div>

<div class="row-fluid">
    <div class="span12">

        <div class="boot-datatable">

            <table class="table table-bordered table-striped datatable">
                <thead>
                <tr>
                    <th width="10"><input type="checkbox" class="trig_bulk_check" name="title-checkbox" /></th>
                    <th class="header" rel="page.page_id">#</th>
                    <!--
                    <th class='header' rel='page.user_id'>User Id</th>
                    <th class='header' rel='page.parent_id'>Parent Id</th>
                    -->
                    <th class='header' rel='page.title'>Title</th>
                    <!--<th class='header' rel='page.content'>Content</th>-->
                    <th class='header' rel='page.permalink'>Permalink</th>
                    <!--<th class='header' rel='page.is_published'>Is Published</th>-->
                    <th class="header" rel="page.created">Created</th>
                    <th width="200"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->data->rows() AS $key=>$value){ ?>
                    <tr>
                        <td><input type="checkbox" data-id="<?php echo $value[$this->primary]; ?>" class="bulk_check"/></td>
                        <td><?php echo $value[$this->primary]; ?></td>
                        <!--
                        <td><?php echo $value['user_id']; ?></td>
                        <td><?php echo $value['parent_id']; ?></td>
                        -->
                        <td><?php echo $value['title']; ?></td>
                        <!--<td><?php echo $value['content']; ?></td>-->
                        <td><?php echo $value['permalink']; ?></td>
                        <!--<td><?php echo $value['is_published']; ?></td>-->
                        <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
                        <td>
                            <a href="/admin/page/id/<?php echo $value[$this->primary]; ?>" class="btn btn-default"><span class="icon-eye-open"> View</span></a>
                            <a href="/admin/delete/?model=Page&id=<?php echo $value[$this->primary];; ?>" rel="model=Page|id=<?php echo $value[$this->primary]; ?>" class="btn btn-default trig_delete"><i class="icon-trash icon-white"></i> Delete</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <form class="form-inline trig_bulk_submit">
            <input type="hidden" id="model" value="Page">
            <div class="form-group">
                <select class="form-control bulk_type">
                    <option value=""></option>
                    <option value="delete">Delete</option>
                </select>
            </div>
            <div class="form-group">
                <button class="form-control" disabled type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
<?php echo $this->pager($this->data->pager(), 'partials/pager/pager.phtml'); ?>
