<?php $params = $this->params;?>
<div class="col-lg-12">
    <div class="panel panel-default" style="margin-bottom: 0 !important;">
        <div class="panel-heading"><strong><?php echo $params['name'];?></strong></div>
        <div class="panel-body">
            <div class="alert alert-info">
                <form class="form-inline trig_role_form">
                    <div class="form-group">Add Child: </div>
                    <div class="form-group">
                        <input type="hidden" name="model" value="Role">
                        <input type="hidden" name="id" value="<?php echo $params['id'];?>">
                        <input type="hidden" name="mptt_left" value="<?php echo $params['left'];?>">
                        <input type="hidden" name="mptt_right" value="<?php echo $params['right'];?>">
                        <input type="text" class="form-control input-sm" name="childName" placeholder="Name">
                    </div>
                    <input type="submit" class="btn btn-info btn-sm" value="Add">
                </form>
            </div>
            <div class="alert alert-danger">
                Delete this Role and Child Roles <button type="button" class="btn btn-danger btn-sm">Delete</button>
            </div>
        </div>
    </div>
</div>