<?php $params = $this->params;?>
<div class="col-lg-12">
    <div class="panel panel-default" style="margin-bottom: 0 !important;">
        <div class="panel-heading"><strong><?php echo $params['name'];?></strong></div>
        <div class="panel-body">
            <div class="alert alert-info">
                <form class="form-inline trig_role_form">
                    <div class="form-group">
                        <input type="hidden" name="model" value="Role">
                        <input type="hidden" name="id" value="<?php echo $params['id'];?>">
                        <input type="hidden" name="mptt_left" value="<?php echo $params['left'];?>">
                        <input type="hidden" name="mptt_right" value="<?php echo $params['right'];?>">
                        <input type="text" class="form-control input-sm" name="childName" placeholder="Name">
                    </div>
                    <div class="form-group">Action: </div>
                    <div class="form-group">
                        <select name="insertAs" class="form-control input-sm">
                            <option value="child">add as child</option>
                            <option value="parent">add as parent</option>
                            <option value="rename">rename item</option>
                        </select>
                    </div>
                    <input type="submit" class="btn btn-info btn-sm pull-right" value="Add">
                </form>
            </div>
            <div class="alert alert-danger">
                <form class="form-inline trig_role_delete">
                    <div class="form-group">Delete this Role and Child Roles</div>
                    <div class="form-group">
                        <input type="hidden" name="model" value="Role">
                        <input type="hidden" name="id" value="<?php echo $params['id'];?>">
                        <input type="hidden" name="mptt_left" value="<?php echo $params['left'];?>">
                        <input type="hidden" name="mptt_right" value="<?php echo $params['right'];?>">
                    </div>
                    <input type="button" class="btn btn-danger btn-sm pull-right" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>